### ISSUE TITLE
Cannot import after building

### ISSUE THREAD

**Issue by bjarnessen** [RiemannAI/openRT#2]
Hello, im trying to use your package. Building the libraries gives warnings:

'
Warning: Extension name 'riemann_theta' does not match fully qualified name 'openRT.riemann_theta' of 'riemann_theta.pyx'
Warning: Extension name 'radius' does not match fully qualified name 'openRT.radius' of 'radius.pyx'
Warning: Extension name 'integer_points' does not match fully qualified name 'openRT.integer_points' of 'integer_points.pyx'
'

But otherwise build OK. When I try to import library i get error:

'
AttributeError: type object 'openRT.riemann_theta.RiemannTheta_Function' has no attribute '__reduce_cython__'
'

It might be a cython issue, its working in python2.7 with cython 0.27.3 but not in python 3 with cython 0.27.3.

Using Anaconda Python 3.6.3, cython 0.26.1, numpy 1.13.3. 

Thanks

Bjarne

**Comment by scarrazza** [comment]
Thanks for the message.

The `setup.py` in this repository is not working properly for python3, however it works fine with python2.7.

In order to avoid this issue you have two options :
- use python2.7

or
- install [RiemannAI/theta](https://github.com/RiemannAI/theta) in python3 and access the Riemann theta function by importing:
```python
import theta.riemann_theta.riemann_theta import RiemannTheta
```

**Comment by bjarnessen** [comment]
Both of these solutions worked for me, thank you very much:) Now I can continue solving my PDE
